### ISSUE TITLE
Allow running daemonized in the cloud (Heroku, etc?)

### ISSUE THREAD

**Issue by patcon** [zeke/remind-me#65]
This tool seems great! I'm curious whether it could be used to replace `/remind` on Slack with something more extensible (for e.g., certain patterns of setting reminders don't work on Slack, and I have no way to improve that tool)

Can you think of a way that this might work? I would imagine a slack integration would need to be able to hit API endpoints in this app in order to set reminders from Slack. Perhaps an MVP replacement of built-in Slack Reminders wouldn't need that.

But running on Heroku or as a CloudRun service (or some such cheap alternative) would be required.

Any thoughts or advice? Happy to think on how to use this more as a library, if that's your preference (to not allow for scope creep!)

Hope you're well!

**Comment by zeke** [comment]
Hey @patcon. This project is unmaintained and I haven't touched it in many years.

You might have to fork it and run with it!

Depending on what you're trying to build, you might be able to use GitHub Actions with scheduled workflows (like cron jobs) to accomplish this kind of thing for free.

**Comment by patcon** [comment]
Thanks @zeke ! I'll close this out then. Thanks for the tips :)
